"use client";

import { designProjects } from "@/data/design-projects";
import { DesignProjectCard } from "@/components/design/DesignGallery";
import { motion } from "framer-motion";
import { activistDesign, designRecognition } from "@/data/design";
import { tools } from "@/data/skills";
import GlassCard from "@/components/ui/GlassCard";
import Section from "@/components/ui/Section";

export default function DesignMedia() { return <Section id="design" eyebrow="Creative practice" title="Design & Media" description="I use design and media as systems for making complex ideas clearer, more useful and easier to act on."><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><GlassCard><p className="text-lg leading-relaxed text-muted">My work spans visual identities, campaign design, editorial layouts, event communication, digital publications, presentations, web content, video editing and audiovisual storytelling. I use those tools across youth activism, student communication, education, institutional branding, nonprofit work and selected brands.</p><div className="mt-8 flex flex-wrap gap-2">{tools.map((tool) => <span key={tool} className="rounded-full border border-border px-3 py-1 text-sm text-muted">{tool}</span>)}</div></GlassCard><GlassCard><p className="text-sm font-medium text-glow">Activism & public-interest communication</p><p className="mt-5 text-3xl font-semibold text-foreground">{activistDesign.materials} visual materials</p><p className="mt-4 leading-relaxed text-muted">{activistDesign.description}</p><div className="mt-6 flex flex-wrap gap-2">{activistDesign.profiles.map((profile) => <span key={profile} className="rounded-full border border-border px-3 py-1 text-sm text-foreground">{profile}</span>)}</div></GlassCard></div><div className="mt-5 grid gap-4 md:grid-cols-3">{designRecognition.map((item, index) => <motion.div key={item} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }}><GlassCard className="h-full"><p className="text-sm leading-relaxed text-muted">{item}</p></GlassCard></motion.div>)}</div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{designProjects.map((project, index) => <DesignProjectCard key={project.slug} project={project} index={index} />)}</div></Section>; }
