"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import { mainProjects, smallerProjects, type Project } from "@/data/projects";
import GlassCard from "@/components/ui/GlassCard";
import Section from "@/components/ui/Section";
import TiltCard from "@/components/ui/TiltCard";

function Tags({ tags, compact = false }: { tags: string[]; compact?: boolean }) { return <div className={`flex flex-wrap ${compact ? "gap-1" : "gap-1.5"}`}>{tags.map((tag) => <span key={tag} className={`rounded-full border border-border text-muted ${compact ? "px-2 py-0.5 text-[10px]" : "px-2.5 py-0.5 text-[11px]"}`}>{tag}</span>)}</div>; }

function MainProjectCard({ project, index }: { project: Project; index: number }) { return <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .07 }}><TiltCard className="h-full"><GlassCard className="group h-full p-0"><div className={`h-20 bg-gradient-to-br sm:h-24 ${project.coverTheme}`}><div className="h-full bg-[radial-gradient(circle_at_75%_20%,rgba(255,255,255,.62),transparent_25%)]" /></div><div className="p-4 sm:p-4.5"><div className="flex items-start justify-between gap-2"><h3 className="text-lg font-semibold leading-tight tracking-[-.03em] text-foreground xl:text-xl">{project.title}</h3>{project.externalUrl && <a href={project.externalUrl} target="_blank" rel="noreferrer" aria-label={`Visit ${project.title}`} className="shrink-0 text-muted transition-transform hover:-translate-y-0.5 hover:translate-x-0.5 hover:text-foreground"><ArrowUpRight size={16} /></a>}</div><p className="mt-2 text-xs leading-relaxed text-muted xl:text-sm">{project.description}</p>{project.awardNote && <p className="mt-3 text-[11px] font-medium leading-relaxed text-foreground">{project.awardNote}</p>}<div className="mt-3"><Tags tags={project.tags} /></div>{project.href && <Link href={project.href} className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-foreground transition-colors hover:text-glow">{project.linkLabel ?? "View project"} <ArrowUpRight size={14} /></Link>}{project.relatedPost && <Link href={`/blog/${project.relatedPost}`} className="mt-4 inline-block text-xs font-medium text-foreground hover:text-glow">Read related Blog post →</Link>}</div></GlassCard></TiltCard></motion.article>; }

function SmallerProjectCard({ project, index }: { project: Project; index: number }) { return <motion.article initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }}><GlassCard className="h-full p-4"><div className={`mb-4 h-2 rounded-full bg-gradient-to-r ${project.coverTheme}`} /><h3 className="text-base font-semibold text-foreground md:text-lg">{project.title}</h3><p className="mt-2 text-xs leading-relaxed text-muted md:text-sm">{project.description}</p><div className="mt-4"><Tags tags={project.tags.slice(0, 3)} compact /></div></GlassCard></motion.article>; }

export default function Projects() { return <Section id="work" eyebrow="Selected work" title="Projects"><div><h3 className="mb-3 text-xs font-medium uppercase tracking-[.18em] text-muted">Main Projects</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{mainProjects.map((project, index) => <MainProjectCard key={project.slug} project={project} index={index} />)}</div></div><div className="mt-6"><h3 className="mb-3 text-xs font-medium uppercase tracking-[.18em] text-muted">More Projects</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{smallerProjects.map((project, index) => <SmallerProjectCard key={project.slug} project={project} index={index} />)}</div></div></Section>; }
