"use client";

import Link from "next/link";
import Image from "next/image";
import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import { OrganizationText } from "@/components/OrganizationLink";
import { mainProjects, smallerProjects, type Project } from "@/data/projects";
import GlassCard from "@/components/ui/GlassCard";
import Section from "@/components/ui/Section";
import TiltCard from "@/components/ui/TiltCard";
import { getCopy, localPath, type Locale } from "@/data/locale";

function Tags({ tags, compact = false }: { tags: string[]; compact?: boolean }) { return <div className={`flex flex-wrap ${compact ? "gap-1" : "gap-1.5"}`}>{tags.map((tag) => <span key={tag} className={`rounded-full border border-border text-muted ${compact ? "px-2 py-0.5 text-[10px]" : "px-2.5 py-0.5 text-[11px]"}`}>{tag}</span>)}</div>; }

const actionClass = "inline-flex items-center gap-2 rounded-full border border-border bg-card/60 px-4 py-2 text-xs font-medium text-foreground shadow-[0_6px_18px_var(--shadow)] backdrop-blur-md transition-all duration-300 hover:border-glow hover:bg-glow/10 hover:text-foreground focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-glow";

function ProjectCover({ project, compact = false, locale }: { project: Project; compact?: boolean; locale: Locale }) { const copy = getCopy(locale).projects; return <div className={`relative overflow-hidden border-b border-border bg-card ${compact ? "h-24" : "h-36 sm:h-40"}`}>{project.coverImage ? <Image src={project.coverImage} alt={`${project.title} project cover`} fill sizes={compact ? "(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 25vw" : "(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 33vw"} className="object-cover transition-transform duration-700 group-hover:scale-[1.03]" /> : <div className="grid h-full place-items-center bg-card px-4 text-center"><span className="text-[11px] font-medium text-muted">{copy.cover}</span></div>}</div>; }

function MainProjectCard({ project, index, locale }: { project: Project; index: number; locale: Locale }) { const copy = getCopy(locale).projects; return <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .07 }}><TiltCard className="h-full"><GlassCard className="group h-full p-0"><ProjectCover project={project} locale={locale} /><div className="flex h-full flex-col p-4 sm:p-4.5"><div className="flex items-start justify-between gap-2"><h3 className="text-lg font-semibold leading-tight tracking-[-.03em] text-foreground xl:text-xl">{project.title}</h3>{project.externalUrl && <a href={project.externalUrl} target="_blank" rel="noopener noreferrer" aria-label={`${copy.visit} ${project.externalLabel ?? project.title}`} className="shrink-0 text-muted transition-transform hover:-translate-y-0.5 hover:translate-x-0.5 hover:text-foreground"><ArrowUpRight size={16} /></a>}</div><p className="mt-2 text-xs leading-relaxed text-muted xl:text-sm"><OrganizationText>{project.description}</OrganizationText></p>{project.awardNote && <p className="mt-3 text-[11px] font-medium leading-relaxed text-foreground">{project.awardNote}</p>}<div className="mt-3"><Tags tags={project.tags} /></div><div className="mt-auto flex flex-wrap gap-2 pt-4">{project.externalUrl && <a href={project.externalUrl} target="_blank" rel="noopener noreferrer" className={actionClass}>{project.externalLabel ?? copy.visit} <ArrowUpRight size={14} /></a>}{project.href && <Link href={localPath(locale, project.href)} className={actionClass}>{project.linkLabel ?? copy.view} <ArrowUpRight size={14} /></Link>}{project.relatedPost && <Link href={localPath(locale, `/blog/${project.relatedPost}`)} className={actionClass}>{copy.related} <ArrowUpRight size={14} /></Link>}</div></div></GlassCard></TiltCard></motion.article>; }

function SmallerProjectCard({ project, index, locale }: { project: Project; index: number; locale: Locale }) { return <motion.article initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }}><GlassCard className="group h-full p-0"><ProjectCover project={project} compact locale={locale} /><div className="p-4"><h3 className="text-base font-semibold text-foreground md:text-lg">{project.title}</h3><p className="mt-2 text-xs leading-relaxed text-muted md:text-sm">{project.description}</p><div className="mt-4"><Tags tags={project.tags.slice(0, 3)} compact /></div></div></GlassCard></motion.article>; }

export default function Projects({ locale }: { locale: Locale }) { const copy = getCopy(locale).projects; return <Section id="work" eyebrow={copy.eyebrow} title={copy.title}><div><h3 className="mb-3 text-xs font-medium uppercase tracking-[.18em] text-muted">{copy.main}</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{mainProjects.map((project, index) => <MainProjectCard key={project.slug} project={project} index={index} locale={locale} />)}</div></div><div className="mt-6"><h3 className="mb-3 text-xs font-medium uppercase tracking-[.18em] text-muted">{copy.more}</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{smallerProjects.map((project, index) => <SmallerProjectCard key={project.slug} project={project} index={index} locale={locale} />)}</div></div></Section>; }
