"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, ExternalLink, MapPin, Building2, CalendarDays } from "lucide-react";
import type { BlogPost } from "@/data/blog";
import BlogCover from "@/components/blog/BlogCover";
import GlassCard from "@/components/ui/GlassCard";

const formatDate = (date: string) => new Intl.DateTimeFormat("en", { day: "numeric", month: "long", year: "numeric" }).format(new Date(`${date}T00:00:00`));

export default function BlogArticle({ post }: { post: BlogPost }) {
  return <main className="min-h-screen bg-background px-6 pb-24 pt-32 text-foreground md:px-8"><article className="mx-auto max-w-4xl"><Link href="/#blog" className="mb-9 inline-flex items-center gap-2 text-sm text-muted transition-colors hover:text-foreground"><ArrowLeft size={16} /> Back to Blog</Link><motion.header initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}><p className="text-sm font-medium text-glow">{post.category}</p><h1 className="mt-4 text-4xl font-bold tracking-[-0.05em] text-foreground md:text-7xl">{post.title}</h1><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted"><span className="inline-flex items-center gap-2"><CalendarDays size={15} />{formatDate(post.date)}</span>{post.organization && <span className="inline-flex items-center gap-2"><Building2 size={15} />{post.organization}</span>}{post.location && <span className="inline-flex items-center gap-2"><MapPin size={15} />{post.location}</span>}</div></motion.header><motion.div initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.7, delay: 0.1 }} className="mt-10"><BlogCover post={post} className="h-72 rounded-[2rem] md:h-[28rem]" /></motion.div><div className="mt-10 space-y-8">{post.content.map((section, index) => <motion.section key={section.heading} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.03 }}><h2 className="text-2xl font-semibold text-foreground">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-3 text-lg leading-relaxed text-muted">{paragraph}</p>)}</motion.section>)}</div><GlassCard className="mt-12"><p className="text-sm font-medium text-glow">Topics</p><div className="mt-4 flex flex-wrap gap-2">{post.tags.map((tag) => <span key={tag} className="rounded-full border border-border px-3 py-1 text-sm text-muted">{tag}</span>)}</div><a href={post.linkedInUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-foreground px-5 py-3 text-sm font-medium text-background transition-transform hover:scale-[1.02]">View original LinkedIn post <ExternalLink size={16} /></a></GlassCard></article></main>;
}
