"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";

type Translation = { title?: string; shortDescription?: string; fullDescription?: string; actionLabel?: string | null };
export type ManagedProject = { slug: string; type: "main" | "smaller" | "design"; status: string; featured: boolean; sortOrder: number; coverImage?: string | null; gallery?: Array<{ src: string; alt?: string; caption?: string }>; tags: string[]; internalRoute?: string | null; externalUrl?: string | null; actionLabel?: string | null; translations: Partial<Record<"en" | "sr", Translation | null>> };
type GalleryImage = { src: string; alt?: string; caption?: string };
const input = "mt-1 w-full rounded-xl border border-border bg-card px-3 py-2 text-foreground";

export default function ProjectEditor({ project }: { project: ManagedProject }) {
  const router = useRouter(); const [locale, setLocale] = useState<"en" | "sr">("en"); const [gallery, setGallery] = useState<GalleryImage[]>(project.gallery ?? []); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const translation = project.translations[locale] ?? project.translations.en ?? {};
  const galleryJson = useMemo(() => JSON.stringify(gallery.filter((image) => image.src.trim())), [gallery]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); setMessage(""); const form = new FormData(event.currentTarget); form.set("locale", locale); form.set("gallery", galleryJson); const response = await fetch("/api/admin/projects", { method: "POST", body: form }); const result = await response.json().catch(() => ({})); setPending(false); if (!response.ok) { setError(result.error || "Saving failed."); return; } setMessage("Saved to GitHub. Vercel will publish this commit automatically."); if (!project.slug && result.slug) router.replace(`/admin/projects/${encodeURIComponent(result.slug)}`); router.refresh(); }
  async function removeProject() { if (!window.confirm("Delete this project? This cannot be undone.")) return; setPending(true); const response = await fetch(`/api/admin/projects?slug=${encodeURIComponent(project.slug)}`, { method: "DELETE" }); const result = await response.json().catch(() => ({})); setPending(false); if (!response.ok) { setError(result.error || "Deleting failed."); return; } router.push("/admin/projects"); router.refresh(); }
  return <form onSubmit={submit} className="glass-card mt-6 grid gap-4 rounded-2xl p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex rounded-xl border border-border bg-card p-1"><button type="button" onClick={() => setLocale("en")} className={`rounded-lg px-3 py-1.5 text-sm ${locale === "en" ? "bg-foreground text-background" : "text-muted"}`}>English</button><button type="button" onClick={() => setLocale("sr")} className={`rounded-lg px-3 py-1.5 text-sm ${locale === "sr" ? "bg-foreground text-background" : "text-muted"}`}>Srpski</button></div><p className="text-xs text-muted">One project, localized content under the same slug.</p></div>
    <div className="grid gap-4 sm:grid-cols-4"><label>Slug<input name="slug" required defaultValue={project.slug} className={input} /></label><label>Collection<select name="type" defaultValue={project.type} className={input}><option value="main">Main project</option><option value="smaller">More project</option><option value="design">Design work</option></select></label><label>Status<select name="status" defaultValue={project.status} className={input}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Sort order<input name="sortOrder" type="number" min="0" defaultValue={project.sortOrder} className={input} /></label></div>
    <label className="flex items-center gap-2 text-sm font-medium"><input name="featured" type="checkbox" defaultChecked={project.featured} /> Featured project</label>
    <label>Title<input name="title" defaultValue={translation.title} required className={input} /></label><label>Short description<textarea name="shortDescription" defaultValue={translation.shortDescription} className={`${input} min-h-24`} /></label><label>Full description<textarea name="fullDescription" defaultValue={translation.fullDescription} className={`${input} min-h-40`} /></label>
    <div className="grid gap-4 sm:grid-cols-3"><label>Tags (comma separated)<input name="tags" defaultValue={project.tags.join(", ")} className={input} /></label><label>Cover image path<input name="coverImage" defaultValue={project.coverImage ?? ""} placeholder="/uploads/image.webp" className={input} /></label><label>Action label<input name="actionLabel" defaultValue={translation.actionLabel ?? project.actionLabel ?? ""} className={input} /></label></div>
    <div className="grid gap-4 sm:grid-cols-2"><label>Internal route<input name="internalRoute" defaultValue={project.internalRoute ?? ""} placeholder="/projects/formula" className={input} /></label><label>External URL<input name="externalUrl" defaultValue={project.externalUrl ?? ""} placeholder="https://…" className={input} /></label></div>
    <section className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-medium">Project gallery</h2><p className="mt-1 text-xs text-muted">Use Media to upload assets, then add their public paths here.</p></div><button type="button" onClick={() => setGallery((items) => [...items, { src: "", alt: "", caption: "" }])} className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-medium hover:border-glow"><Plus size={14} /> Add image</button></div><div className="mt-4 grid gap-3">{gallery.map((image, index) => <div key={index} className="grid gap-2 rounded-xl border border-border p-3 sm:grid-cols-[1.2fr_1fr_1fr_auto]"><label className="text-xs">Image path<input value={image.src} onChange={(event) => setGallery((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, src: event.target.value } : item))} className={input} /></label><label className="text-xs">Alt text<input value={image.alt ?? ""} onChange={(event) => setGallery((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, alt: event.target.value } : item))} className={input} /></label><label className="text-xs">Caption<input value={image.caption ?? ""} onChange={(event) => setGallery((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, caption: event.target.value } : item))} className={input} /></label><button type="button" aria-label="Remove image" onClick={() => setGallery((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="self-end rounded-lg border border-border p-2 text-muted hover:text-red-500"><Trash2 size={15} /></button></div>)}</div></section>
    {error && <p role="alert" className="text-sm text-red-500">{error}</p>}{message && <p role="status" className="text-sm text-glow">{message}</p>}<div className="flex flex-wrap gap-3"><button disabled={pending} className="w-fit rounded-full bg-foreground px-5 py-2.5 text-sm font-medium text-background disabled:opacity-60">{pending ? "Saving…" : "Save and commit"}</button><button type="button" disabled={pending} onClick={removeProject} className="rounded-full border border-red-500/40 px-5 py-2.5 text-sm font-medium text-red-500 hover:bg-red-500/10">Delete project</button></div>
  </form>;
}
