create type public.content_status as enum ('draft', 'published', 'archived');
create table public.posts (id uuid primary key default gen_random_uuid(), slug text unique not null, status public.content_status not null default 'draft', published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), cover_image_url text, source_url text, location text, organization text, featured boolean not null default false, sort_order integer not null default 0);
create table public.post_translations (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, locale text not null check (locale in ('en','sr')), title text not null, excerpt text not null, body text not null default '', seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(post_id, locale));
create table public.projects (id uuid primary key default gen_random_uuid(), slug text unique not null, type text not null default 'project', status public.content_status not null default 'draft', cover_image_url text, external_url text, internal_route text, featured boolean not null default false, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_translations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, locale text not null check (locale in ('en','sr')), title text not null, short_description text not null, full_description text, action_label text, seo_title text, seo_description text, unique(project_id, locale));
create table public.project_media (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, file_url text not null, file_type text not null, alt_text_en text, alt_text_sr text, caption_en text, caption_sr text, sort_order integer not null default 0);
create table public.site_sections (id uuid primary key default gen_random_uuid(), section_key text not null, locale text not null check (locale in ('en','sr')), title text, subtitle text, body text, structured_content jsonb, updated_at timestamptz not null default now(), unique(section_key, locale));
alter table public.posts enable row level security; alter table public.post_translations enable row level security; alter table public.projects enable row level security; alter table public.project_translations enable row level security; alter table public.project_media enable row level security; alter table public.site_sections enable row level security;
create policy "published posts are public" on public.posts for select using (status = 'published');
create policy "published post translations are public" on public.post_translations for select using (exists(select 1 from public.posts where posts.id = post_translations.post_id and posts.status = 'published'));
create policy "published projects are public" on public.projects for select using (status = 'published');
create policy "published project translations are public" on public.project_translations for select using (exists(select 1 from public.projects where projects.id = project_translations.project_id and projects.status = 'published'));
create policy "published project media is public" on public.project_media for select using (exists(select 1 from public.projects where projects.id = project_media.project_id and projects.status = 'published'));
create policy "site sections are public" on public.site_sections for select using (true);
-- No public write policies: server-side service role is required for all administration mutations.
insert into storage.buckets (id, name, public) values ('portfolio-media', 'portfolio-media', true) on conflict (id) do nothing;
alter table storage.objects enable row level security;
create policy "public reads portfolio media" on storage.objects for select using (bucket_id = 'portfolio-media');
